### ISSUE TITLE
SNMP V2c support

### ISSUE THREAD

**Issue by Dh0mp5eur** [lcafaro/snmphp#1]
Hi

Demo_bootstrap work fine with HP A5500.
But it work with SNMP V1 and SNMP V2c is better.

Is possible to add SNMP V2c support?

Thx

**Comment by lcafaro** [comment]
Hello,

I've added SNMP v2c support.

Just add it to the constructor call, for example:

```$hp1920 = new procurve("192.168.10.3", "public", "2c");```

I've tested this on 1920-48G and it seems to work fine. Let me know if you encounter any issues.

Thanks

**Comment by lcafaro** [comment]
Also, if you forked this code already and have made no changes, I suggest you sync it from the current master (or delete and refork :-) since I've done a few more fixes other than v2c support (corrected indentation, removed a few requests to unavailable files and deleted unused variables).

Thanks

**Comment by Dh0mp5eur** [comment]
Hi,

Thank you so much.
It's work fine.

With better web interface, it will be a very tool.
Thnaks for your work.
